name: Ritchie Construction Ltd
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5753989068325609
title: Ritchie Construction - General Contractor - Renovations - New Homes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#484641'
    - '#004080'
    - '#000000'
    - '#0000ff'
    - '#550000'
  brandStrength: 0.48353259661234915
  lightness: 0.033064914867281914
  saturation: 0.03422369807958603
  rhythmicContrast: 0.8190976050682366
purpose: []
